
services:
  postgres:
    image: postgres:16
    container_name: payment_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: 
      - "5432:5432"
    volumes:
      - distributed_financial_ledger:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: payment_db_migrate
    volumes:
      - ./src/database/migrations:/migrations
    command: [
      "-path",
      "/migrations",
      "-database",
      "postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/payment_db?sslmode=disable",
      "up"
    ]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  distributed_financial_ledger:


#   api:
#     build: .
#     container_name: lendsqr_backend
#     command: npm run dev
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules
#     ports:
#       - "3000:3000"
#     env_file:
#       - .env
#     depends_on:
#       - mysql

# volumes:
#   mysql_data:
