// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/deposit": {
            "post": {
                "description": "Credits funds to an account from the system settlement account. Supports idempotent deposits.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deposits"
                ],
                "summary": "Deposit funds to account",
                "parameters": [
                    {
                        "description": "Deposit Details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.DepositParams"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/routes.TransferResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/account/number/{number}": {
            "get": {
                "description": "Retrieves account details by its account number.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Get account by account number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account number",
                        "name": "number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.AccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/account/transfer": {
            "post": {
                "description": "Creates a money transfer from one account to another with automatic fee collection. Supports idempotent transfers.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transfers"
                ],
                "summary": "Create a transfer between accounts",
                "parameters": [
                    {
                        "description": "Transfer Details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.TransferParams"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/routes.TransferResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/account/withdraw": {
            "post": {
                "description": "Debits funds from an account to the system settlement account. Supports idempotent withdrawals.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Withdrawals"
                ],
                "summary": "Withdraw funds from account",
                "parameters": [
                    {
                        "description": "Withdrawal Details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.WithddrawParams"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/routes.TransferResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/account/{id}/balances": {
            "get": {
                "description": "Retrieves all balance information for an account including ledger, available, and held amounts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Balances"
                ],
                "summary": "Get balances for account",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Account UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.BalanceResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/admin/hold/consume": {
            "post": {
                "description": "Converts a held amount to an actual debit and releases remaining funds.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Consume a hold",
                "parameters": [
                    {
                        "description": "Hold Consumption Details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.HoldParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/admin/hold/{transfer_id}": {
            "get": {
                "description": "Retrieves the active hold placed on a transfer for payment processing.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get active hold for transfer",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Transfer request UUID",
                        "name": "transfer_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.HoldResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/create/account": {
            "post": {
                "description": "Creates a new account for a customer. Idempotent by external_ref and account_number.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Create a new account",
                "parameters": [
                    {
                        "description": "Account Creation Details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.AccountParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.AccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/create/user": {
            "post": {
                "description": "Creates a new customer account with the provided information. Idempotent by external_ref.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create a new customer/user",
                "parameters": [
                    {
                        "description": "User Creation Details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.parameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/err": {
            "get": {
                "description": "Testing endpoint for error handling validation.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Error test endpoint",
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns 200 OK if the service is alive and responding. Used for liveness probes.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/list/accounts/customer": {
            "post": {
                "description": "Returns paginated list of accounts owned by a specific customer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "List accounts for a customer",
                "parameters": [
                    {
                        "description": "Customer ID and Pagination details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.AccountParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.AccountResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/list/users": {
            "post": {
                "description": "Returns paginated list of customers with optional limit and offset.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "List customers with pagination",
                "parameters": [
                    {
                        "description": "Pagination details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.parameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.UserResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/transfer/{id}": {
            "get": {
                "description": "Retrieves details of a specific transfer transaction.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transfers"
                ],
                "summary": "Get transfer by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Transfer UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/routes.TransferResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/update/account": {
            "post": {
                "description": "Updates the status of an existing account (e.g., active, suspended, closed).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Update account status",
                "parameters": [
                    {
                        "description": "Account ID and New Status",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.AccountParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.AccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/update/user": {
            "post": {
                "description": "Updates the status of an existing customer (e.g., active, inactive, suspended).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user status",
                "parameters": [
                    {
                        "description": "User Status Update Details (requires id and status)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.parameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "description": "Retrieves a specific customer by their UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Customer UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        },
        "/webhook/paystack": {
            "post": {
                "description": "Receives webhook events from Paystack. Supported events: transfer.success, transfer.failed, transfer.reversed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhooks"
                ],
                "summary": "Paystack webhook endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA512 signature",
                        "name": "X-Paystack-Signature",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Webhook Payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.WebhookBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.errResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "routes.AccountParameters": {
            "type": "object",
            "properties": {
                "account_number": {
                    "type": "string"
                },
                "account_type": {
                    "type": "string"
                },
                "currency_code": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "string"
                },
                "external_ref": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ledger_normal_side": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "offset": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "routes.AccountResponse": {
            "type": "object",
            "properties": {
                "account_number": {
                    "type": "string"
                },
                "account_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "currency_code": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ledger_normal_side": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "routes.BalanceResponse": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "as_of": {
                    "description": "when projection was computed",
                    "type": "string"
                },
                "available_balance": {
                    "description": "spendable right now",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.MoneyAmount"
                        }
                    ]
                },
                "currency": {
                    "type": "string"
                },
                "held_balance": {
                    "description": "reserved, not yet debited",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.MoneyAmount"
                        }
                    ]
                },
                "ledger_balance": {
                    "description": "total ever posted",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.MoneyAmount"
                        }
                    ]
                }
            }
        },
        "routes.DepositeParams": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "client_reference": {
                    "type": "string"
                },
                "currency_code": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "destination_account_id": {
                    "type": "string"
                },
                "external_reference": {
                    "type": "string"
                },
                "fee_amount": {
                    "type": "string"
                },
                "idempotency_key_id": {
                    "type": "string"
                },
                "memo": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "source_account_id": {
                    "type": "string"
                },
                "source_system": {
                    "type": "string"
                }
            }
        },
        "routes.HoldParams": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "original hold amount",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "reason_code": {
                    "type": "string"
                },
                "transfer_id": {
                    "type": "string"
                }
            }
        },
        "routes.HoldResponse": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "amount": {
                    "description": "original hold amount",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.MoneyAmount"
                        }
                    ]
                },
                "captured_amount": {
                    "description": "converted to real debit",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.MoneyAmount"
                        }
                    ]
                },
                "captured_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "reason_code": {
                    "type": "string"
                },
                "released_amount": {
                    "description": "returned to available",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.MoneyAmount"
                        }
                    ]
                },
                "released_at": {
                    "type": "string"
                },
                "remaining_amount": {
                    "description": "still locked",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.MoneyAmount"
                        }
                    ]
                },
                "status": {
                    "description": "\"active\" | \"consumed\" | \"released\" | \"expired\"",
                    "type": "string"
                }
            }
        },
        "routes.MoneyAmount": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "always a string — never float for money",
                    "type": "string"
                },
                "currency": {
                    "description": "\"NGN\"",
                    "type": "string"
                }
            }
        },
        "routes.TransferParams": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "client_reference": {
                    "type": "string"
                },
                "currency_code": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "destination_account_id": {
                    "type": "string"
                },
                "external_reference": {
                    "type": "string"
                },
                "fee_amount": {
                    "type": "string"
                },
                "idempotency_key_id": {
                    "type": "string"
                },
                "memo": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "source_account_id": {
                    "type": "string"
                },
                "source_system": {
                    "type": "string"
                }
            }
        },
        "routes.TransferResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "$ref": "#/definitions/routes.MoneyAmount"
                },
                "client_reference": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "destination_account_id": {
                    "type": "string"
                },
                "external_reference": {
                    "type": "string"
                },
                "failure_code": {
                    "type": "string"
                },
                "failure_reason": {
                    "type": "string"
                },
                "fee": {
                    "$ref": "#/definitions/routes.MoneyAmount"
                },
                "id": {
                    "type": "string"
                },
                "journal_transaction_id": {
                    "type": "string"
                },
                "posted_at": {
                    "type": "string"
                },
                "requested_at": {
                    "type": "string"
                },
                "source_account_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "routes.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "external_ref": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "national_id": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "routes.WebhookBody": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "event": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "routes.WithddrawParams": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "client_reference": {
                    "type": "string"
                },
                "currency_code": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "destination_account_id": {
                    "type": "string"
                },
                "external_reference": {
                    "type": "string"
                },
                "fee_amount": {
                    "type": "string"
                },
                "idempotency_key_id": {
                    "type": "string"
                },
                "memo": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "source_account_id": {
                    "type": "string"
                },
                "source_system": {
                    "type": "string"
                }
            }
        },
        "routes.errResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "routes.parameters": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "external_ref": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "idemp_key": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "national_id": {
                    "type": "string"
                },
                "offset": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Distributed Payments Engine API",
	Description:      "A comprehensive distributed payment processing system with support for transfers, deposits, withdrawals, and holds.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
